default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: snowdrop_development

test:
  <<: *default
  database: snowdrop_test

production:
  <<: *default
  database: snowdrop_production
  username: deploy
  password: <%= Rails.application.credentials.dig(:production, :db, :password) %>
